
services:
  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - app_net
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ~/.pg/pg_data/flask-yt/:/var/lib/postgresql/data


  flask:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: flask
    networks:
      - app_net
    volumes:
      - ~/.uploads/images/flask-yt:/app/habit_tracker/static/upload
    env_file:
      - .env
    environment:
      POSTGRESQL_HOST: ${POSTGRESQL_HOST}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DB: ${POSTGRESQL_DB}
    depends_on:
        - postgres
    expose:
      - 8080

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: nginx
    networks:
      - app_net
    env_file:
      - .env
    depends_on:
      - flask
    ports:
      - "8080:80"

volumes:
  postgres_data:

networks:
  app_net:

