[uwsgi]
wsgi-file = run.py
callable = application
plugins = python3
socket = :8080
processes = 4
threads = 2
master = true
die-on-term = true
vacuum = true
chdir = /app
uid = nobody
gid = nogroup
logto = /dev/stdout